name: Build

on:
  push:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Ktlint
        run: ./gradlew ktlintFormat

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Run JaCoCo
        run: ./gradlew jacocoFullTestReport

      - name: Build app
        run: ./gradlew build
