# Workflow name
name: Build
on:
  # When it will be triggered
  # And in which branch
  pull_request:
  push:
    branches:
      - main
# Where will they run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up our JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Run Ktlint
        run: ./gradlew ktlintFormat

      - name: Run tests
        run: ./gradlew testDebugUnitTest

      - name: Run JaCoCo
        run: ./gradlew jacocoFullTestReport

      - name: Build the app
        run: ./gradlew build